Water Sensor shown on display with icons
rancilio-pid/clevercoffee pull request #403
Opened 2023-12-03 16:53 UTC by genkigenki

Water Sensor, "water empty" icon shown in top right, on each display mode
In case the water sensor is not configured, water_full=true always, so no icon will ever be shown.

2023-12-03 18:48 UTC, fiendie requested changes

2023-12-03 19:16 UTC, genkigenki commented on src/display.h
> +		}
looks good with VS code
![grafik](https://github.com/rancilio-pid/clevercoffee/assets/3080081/3296490a-ea5a-4e96-a2ef-610861066913)

2023-12-03 19:19 UTC, genkigenki commented on src/main.cpp
> +                } else {
ok done at all 3 positions

2023-12-03 19:20 UTC, genkigenki commented on src/main.cpp
> +            } else {
Resolved.
However, in the whole code there are many instances like this.

2023-12-04 20:24 UTC, genkigenki commented on src/display.h
> +        if (waterFull == false) {
done

2023-12-05 17:40 UTC, fiendie requested changes

2023-12-05 17:40 UTC, fiendie commented on src/main.cpp
> +
Can be shortened to #if ... #elif ... #endif
I know it's not consistent in the codebase but while we're at it :)

2023-12-11 09:31 UTC, fiendie approved these changes

2024-01-08 17:32 UTC, fiendie approved these changes

2024-01-08 17:32 UTC, merged