Menu with Rotary Encoder
rancilio-pid/clevercoffee pull request #419
Opened 2023-12-12 14:40 UTC by FabianSperrle

New PR as I migrated the implementation to a branch in my fork.

- Use ESP32-specific libraries for button and encoder that should use as many of the new fancy functions the platform has to offer as possible, while reducing the need for both timer interrupts and actual interrupts. 
- Cherry-picked fixes/improvements from @fiendie 
- Merged in the latest master 

I've only seen a single temp error since I introduced the changes... The website works smoothly on two clients simultaneously.

TODO:

- [x] Add all other options from the website to the menu
- [ ] Test on other machines :-)

2023-12-12 15:16 UTC, LoQue90 commented
I will do a upgrade of my mashine soon. There i will add the rotary to my setup to give this a real world try :)
Thanks for your work!

2024-01-22 07:35 UTC, fiendie requested changes

2024-01-22 07:35 UTC, fiendie commented on src/menu.h
> +// -------------------
No ASCII art please :)

2024-01-22 07:35 UTC, fiendie commented on src/display.h
> +    switch (mode) {
For 1 and 0 this should probably not be a switch statement. 

if (mode == 1) will be a lot more readable. 

If there are more than 2 modes then a switch statement might be OK, but the magic numbers should then be replaced by an enum.

2024-01-22 07:35 UTC, fiendie commented on src/main.cpp
> +        if (menuOpen == false) {
Could be shortened to if (!menuOpen) like you did a few lines further down  :)

2024-01-22 07:35 UTC, fiendie commented on src/menu.h
> +    // init vars
Commented out code should be removed

2024-01-22 07:35 UTC, fiendie commented on src/menu.h
> +        debugPrintln(F("================  Menu ===================="));
See above

2024-01-22 07:35 UTC, fiendie commented on src/menu.h
> +        // ***************
See above

2024-01-22 07:35 UTC, fiendie commented on src/menu.h
> +        // ***************
See above

2024-01-22 07:35 UTC, fiendie commented on src/menu.h
> +            // increment some values
This comment contains no information that isn't perfectly obvious from the 2 lines of code below :)

2024-01-22 07:35 UTC, fiendie commented on src/menu.h
> +
Blank line can be removed

2024-01-27 18:29 UTC, FabianSperrle commented
No longer works with `espressif32 @^6.4.0`. Opening the menu causes a reboot, see stack trace below. Might need to find another encoder lib again, but my motivation is somewhat limited... 

```
[00:02:36] Opening Menu!

abort() was called at PC 0x4008556f on core 1


Backtrace: 0x40083ee9:0x3ffcfd80 0x4008d361:0x3ffcfda0 0x400929e5:0x3ffcfdc0 0x4008556f:0x3ffcfe40 0x400856b9:0x3ffcfe70 0x40085755:0x3ffcfe90 0x40181652:0x3ffcfec0 0x40184685:0x3ffd01d0 0x401987bd:0x3ffd0200 0x401290be:0x3ffd0230 0x4012915b:0x3ffd0260 0x400fb999:0x3ffd02e0 0x400f5879:0x3ffd0320 0x400f590a:0x3ffd0350 0x400d45e6:0x3ffd0370 0x400f523d:0x3ffd0390 0x400f57ca:0x3ffd03b0 0x400dcde5:0x3ffd03d0 0x400fa5a1:0x3ffd03f0

  #0  0x40083ee9:0x3ffcfd80 in panic_abort at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/panic.c:408
  #1  0x4008d361:0x3ffcfda0 in esp_system_abort at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/esp_system.c:137
  #2  0x400929e5:0x3ffcfdc0 in abort at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/newlib/abort.c:46
  #3  0x4008556f:0x3ffcfe40 in lock_acquire_generic at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/newlib/locks.c:139
  #4  0x400856b9:0x3ffcfe70 in _lock_acquire_recursive at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/newlib/locks.c:167
  #5  0x40085755:0x3ffcfe90 in __retarget_lock_acquire_recursive at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/newlib/locks.c:323
  #6  0x40181652:0x3ffcfec0 in _vfprintf_r at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/stdio/vfprintf.c:853 (discriminator 2)
  #7  0x40184685:0x3ffd01d0 in vprintf at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/stdio/vprintf.c:34 (discriminator 5)
  #8  0x401987bd:0x3ffd0200 in esp_log_writev at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/log/log.c:200
  #9  0x401290be:0x3ffd0230 in __wrap_esp_log_writev at /Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/esp-rainmaker/components/esp-insights/components/esp_diagnostics/src/esp_diagnostics_log_hook.c:452
  #10 0x4012915b:0x3ffd0260 in __wrap_esp_log_write at /Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/esp-rainmaker/components/esp-insights/components/esp_diagnostics/src/esp_diagnostics_log_hook.c:469
  #11 0x400fb999:0x3ffd02e0 in _pcnt_get_counter_value at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/driver/pcnt.c:98
      (inlined by) pcnt_get_counter_value at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/driver/pcnt.c:434
  #12 0x400f5879:0x3ffd0320 in ESP32Encoder::getCountRaw() at .pio/libdeps/esp32_usb/ESP32Encoder/src/ESP32Encoder.cpp:262
  #13 0x400f590a:0x3ffd0350 in ESP32Encoder::getCount() at .pio/libdeps/esp32_usb/ESP32Encoder/src/ESP32Encoder.cpp:279
  #14 0x400d45e6:0x3ffd0370 in menuControls() at src/menu.h:311
  #15 0x400f523d:0x3ffd0390 in LCDMenuLib2::loop_control() at .pio/libdeps/esp32_usb/LCDMenuLib2/src/LCDMenuLib2.cpp:138
  #16 0x400f57ca:0x3ffd03b0 in LCDMenuLib2::loop() at .pio/libdeps/esp32_usb/LCDMenuLib2/src/LCDMenuLib2.cpp:122
  #17 0x400dcde5:0x3ffd03d0 in loop() at src/main.cpp:2319
  #18 0x400fa5a1:0x3ffd03f0 in loopTask(void*) at C:/Users/Fabian/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:50




ELF file SHA256: 63f3db972ee7e596

Rebooting...
```

2024-05-24 22:52 UTC, closed without merging