RGB LEDs as state indicators with animations, cup illumination, etc
rancilio-pid/clevercoffee pull request #444
Opened 2024-01-21 19:18 UTC by genkigenki

Added FastLED library, and LED handling for Neopixels with e.g. WS2811 chip.
LoopLED will be called every 20ms for smooth LED animations.
Number of LEDs and chip type is freely configurable.
Library is using Hardware features of ESP32 to avoid interrup conflicts
2 LED behaviours added to select from: Basic & Colorful

Colorful:
Heating to setpoint or Standby -> Default: switch all LEDs off
Perfect temp -> Green, one LED in back of machine
Brew/Steam/Backflush -> white
After coffee is brewed -> White light to show ready coffee for 15s, for the last 10% of the time, smoothly dim down
Initialize, cold start Heat up --> Rainbow (only if configured)
Error message: Red heartbeat (Water empty, sensor error, etc) 
Steam-heat-up -> yellow

2024-01-23 00:00 UTC, LoQue90 requested changes

2024-01-28 21:17 UTC, genkigenki commented on src/main.cpp
> +#define PIDON_LED_BRIGHTNESS 50
Userconfig - its already quite a few settings for the LEDs, would keep that standard.
Defaults.h would be possible - but to me it seems these are the values which will be saved and are possible to change via web interface?

2024-01-28 21:19 UTC, genkigenki commented on src/StatusLEDvoid.h
> +            brightnessLED = (brewFinishedLEDon > (BREW_FINISHED_LEDON_DURATION / 10) ? 200 : 150*brewFinishedLEDon*10/BREW_FINISHED_LEDON_DURATION+PIDON_LED_BRIGHTNESS);
OK!

2024-01-28 21:19 UTC, genkigenki commented on src/StatusLEDvoid.h
> +                fill_solid(leds, NUM_LEDS, CHSV(0, 250, cubicwave8(cycleLED*4))); //Hue of 0 is red
OK!

2024-01-28 21:20 UTC, genkigenki commented on src/brewvoid.h
> +                    if (brewFinishedLEDon==0)
OK

2024-01-28 21:35 UTC, LoQue90 commented on src/main.cpp
> +#define PIDON_LED_BRIGHTNESS 50
If you program it to be configured via web interface, standard values should be then in defaults.h

2024-01-28 21:37 UTC, genkigenki commented on src/main.cpp
> +#define PIDON_LED_BRIGHTNESS 50
Wouldnt configure it there. 
If i just want to keep it constant would it be OK like that?

2024-01-28 21:40 UTC, LoQue90 commented on src/main.cpp
> +#define PIDON_LED_BRIGHTNESS 50
That was my first question, if this is something that the user should be able to configure. A brightness is something that I would like to set myself. 
It's just my thoughts about that.

2024-01-28 21:47 UTC, genkigenki commented on src/main.cpp
> +#define PIDON_LED_BRIGHTNESS 50
OK good idea, made the "machine on" brightness configurable in userconfig.

2024-03-05 00:42 UTC, closed without merging