Show "manual flush" on Display with Temperature
rancilio-pid/clevercoffee pull request #447
Opened 2024-01-27 12:46 UTC by genkigenki

Show "manual flush" on Display with Temperature

2024-01-27 12:50 UTC, fiendie commented
You committed a backup of your userConfig.h
Also, if you're already rebasing, please squash the "Rebase" commit into the previous one.

2024-01-27 13:05 UTC, genkigenki commented
> You committed a backup of your userConfig.h Also, if you're already rebasing, please squash the "Rebase" commit into the previous one.

Done.

2024-01-27 17:52 UTC, genkigenki commented
Changed:
- Showing brewtime (hint from @LoQue90 - thanks)
- Moved duplicated code to show brew time into function
- Analogous to the "°" for temperature, added small "s" for the brewtime as physical unit (as we also have weight now)

2024-02-11 01:14 UTC, LoQue90 commented
rebase just works, nothing to do here.
I just moved some lines, just style cleanup.
removed "and rebase" from the commit
if you want just pull: https://github.com/LoQue90/clevercoffee/tree/manuall_flush

2024-02-11 01:39 UTC, LoQue90 requested changes

2024-02-11 01:39 UTC, LoQue90 commented on src/display.h
> +
remove empty line

2024-02-11 01:39 UTC, LoQue90 commented on src/display.h
> +    u8g2.print("s");
add empty line before

2024-02-11 01:39 UTC, LoQue90 commented on src/display.h
> +
remove empty line

2024-02-11 11:42 UTC, merged