Make Water Sensor an IOSwitch
rancilio-pid/clevercoffee pull request #490
Opened 2024-04-13 08:59 UTC by simonspa

2024-04-13 19:26 UTC, fiendie requested changes

2024-04-13 19:26 UTC, fiendie commented on src/main.cpp
> +        if (isWaterDetected && !waterFull) {
Missing blank line

2024-04-13 19:31 UTC, simonspa commented on src/main.cpp
> +        if (isWaterDetected && !waterFull) {
Fixed.

2024-04-13 19:40 UTC, fiendie approved these changes

2024-04-13 19:41 UTC, fiendie submitted a review, later dismissed

2024-04-14 21:56 UTC, simonspa commented
Is rebased.

2024-04-14 22:13 UTC, LoQue90 approved these changes

2024-04-14 22:13 UTC, merged